name: joya_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  http: ^1.4.0
  shimmer: ^3.0.0
  multi_select_flutter: ^4.1.3
  image_picker_for_web: ^3.0.6
  url_launcher: ^6.3.1
  intl: ^0.20.2
  salomon_bottom_bar: ^3.3.2
  flutter_svg: ^2.2.0
  smooth_page_indicator: ^1.2.1
  # flutter_file_picker_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/joya.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/joya.png"
